#!/usr/bin/env swift
import Foundation

// Generates macos/Sources/Translate/LanguageCatalog+Generated.swift from the
// canonical languages.tsv at the repo root. Idempotent: re-running on an
// unchanged TSV produces byte-identical output. Run from anywhere:
//
//   swift scripts/gen-language-catalog.swift
//
// A CI / pre-commit drift guard (scripts/check-language-catalog.sh) re-runs this
// and `git diff --exit-code`s the generated file so the TSV and the embedded
// Swift catalog can never silently diverge.

let scriptURL = URL(fileURLWithPath: #filePath)
let repoRoot = scriptURL.deletingLastPathComponent().deletingLastPathComponent()
let tsvURL = repoRoot.appendingPathComponent("languages.tsv")
let outURL = repoRoot.appendingPathComponent("macos/Sources/Translate/LanguageCatalog+Generated.swift")

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data("gen-language-catalog: \(message)\n".utf8))
    exit(1)
}

guard let raw = try? String(contentsOf: tsvURL, encoding: .utf8) else {
    fail("cannot read \(tsvURL.path)")
}

func swiftString(_ value: String) -> String {
    let escaped = value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
    return "\"\(escaped)\""
}

func optionalSwiftString(_ value: String) -> String {
    value.isEmpty ? "nil" : swiftString(value)
}

func aliasesLiteral(_ field: String) -> String {
    let parts = field
        .split(separator: ",")
        .map { $0.trimmingCharacters(in: .whitespaces) }
        .filter { !$0.isEmpty }
    guard !parts.isEmpty else { return "[]" }
    return "[" + parts.map(swiftString).joined(separator: ", ") + "]"
}

var entries: [String] = []
var seenCodes = Set<String>()

for (index, rawLine) in raw.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
    let line = rawLine.hasSuffix("\r") ? String(rawLine.dropLast()) : String(rawLine)
    if line.trimmingCharacters(in: .whitespaces).isEmpty { continue }

    let cols = line.components(separatedBy: "\t")
    if index == 0, cols.first == "code" { continue } // header

    guard cols.count >= 5 else {
        fail("row \(index + 1): expected at least 5 columns, got \(cols.count)")
    }
    let code = cols[0]
    let englishName = cols[1]
    let endonym = cols[2]
    let googleCode = cols[3]
    let aiName = cols[4]
    let aliases = cols.count >= 6 ? cols[5] : ""

    guard !code.isEmpty, !googleCode.isEmpty else {
        fail("row \(index + 1): code and googleCode must be non-empty")
    }
    guard seenCodes.insert(code).inserted else {
        fail("duplicate code \(code) on row \(index + 1)")
    }

    entries.append(
        "        Language(code: \(swiftString(code)), englishName: \(swiftString(englishName)), "
        + "endonym: \(swiftString(endonym)), googleCode: \(swiftString(googleCode)), "
        + "aiName: \(optionalSwiftString(aiName)), aliases: \(aliasesLiteral(aliases))),"
    )
}

guard !entries.isEmpty else { fail("no language rows found in \(tsvURL.path)") }

let header = """
// Generated by scripts/gen-language-catalog.swift from languages.tsv.
// DO NOT EDIT BY HAND. Run `swift scripts/gen-language-catalog.swift` to regenerate.

extension LanguageCatalog {
    /// The full Google-Translate-supported catalog, generated from languages.tsv.
    static let all: [Language] = [
"""

let footer = """
    ]
}
"""

let body = ([header] + entries + [footer]).joined(separator: "\n") + "\n"

do {
    try body.write(to: outURL, atomically: true, encoding: .utf8)
} catch {
    fail("cannot write \(outURL.path): \(error)")
}

FileHandle.standardError.write(
    Data("gen-language-catalog: wrote \(entries.count) languages to \(outURL.path)\n".utf8)
)
